LIBNAME SASDATA 'L:\PREHCO PAPER' ;
RUN;

DATA ONE; SET SASDATA.PREHCO_WAVE1;
RUN;
PROC SORT; BY CASEID;
RUN;
DATA TWO; SET SASDATA.PREHCO_WAVE2;
RUN;
PROC SORT; BY CASEID;
RUN;
DATA THREE;
MERGE ONE (IN=A) TWO (IN=B); BY CASEID;
RUN;

DATA FOUR;
SET THREE;
*NUMBER IN HOUSEHOLD;
IF C1NUM LT 0 THEN C1NUM =.;
IF FINALSCR LT 0 THEN FINALSCR =.;
IF WFINSCR LT 0 THEN WFINSCR =.;
*AGE;
IF EDAD_R1 LT 0 THEN EDAD_R1 =.;
IF WEDA_R1 LT 0 THEN WEDA_R1 =.;
IF C8R1 LT 0 THEN C8R1 =.;
IF C10R1 LT 0 THEN C10R1 =.;
*GDS;
IF DEPRE_Y LT 0 THEN DEPRE_Y = A;
IF WDEPRE_Y LT 0 THEN WDEPRE_Y =.;
IF E3 LT 0 THEN E3 =.;
*HEALTH CONDITIONS CODED NO IF IDK;
IF G4 LT 0 THEN G4 =2;
IF G8 LT 0 THEN G8 =2;
IF G35 LT 0 THEN G35 =2;
IF G36 LT 0 THEN G36 =2;
IF G40 LT 0 THEN G40 =2;
IF RBMI LT 0 THEN RBMI=.;
*AGE DIABETES ONSET;
IF G8AEDAD LT 0 THEN G8AEDAD =.;
IF G9 LT 0 THEN G9 =2;
*CODE DIABETES BEHAVIORS AS "NO" FOR PEOPLE MISSING CUZ DON'T HAVE DIABETES;
IF G10 LT 0 THEN G10 =2;
IF G11 LT 0 THEN G11 =2;
IF G12 LT 0 THEN G12 =1;
IF G13 LT 0 THEN G13 =2;
IF G14 LT 0 THEN G14 =.;
IF G15 LT 0 THEN G15 =.;
IF G16 LT 0 THEN G16 =2;
IF G17 LT 0 THEN G17 =2;
IF G18 LT 0 THEN G18 =2;
IF G19 LT 0 THEN G19 =2;
IF G20 LT 0 THEN G20 =2;
IF G21 LT 0 THEN G21 =2;

*CHILDHOOD CONDITIONS;
IF H2A LT 0 THEN H2A =.;
IF H3A LT 0 THEN H3A =.;
IF H6A LT 0 THEN H6A =.;
IF H6C LT 0 THEN H6C =.;
IF H8 LT 0 THEN H8=.;
IF H15 LT 0 THEN H15=.;
IF H1 LT 0 THEN H1=.;
IF H2 LT 0 THEN H2=.;
IF O2 LT 0 THEN O2=.;

IF K25 LT 0 THEN K25 =.;
IF M1O LT 0 THEN M1O =.;
IF R2 LT 0 THEN R2 =.;
IF R1 LT 0 THEN R1 =.;
IF C8R1 LT 0 THEN C8R1 =.;
IF J12 LT 0 THEN J12 =.;
IF G126 LT 0 THEN G126=.;
*KNEE HEIGHT;
IF U5_P LT 0 THEN U5_P=.;

*ADULT SES;
IF N71 LT 0 THEN N71=.;
IF N72 LT 0 THEN N72=.;

AGE = EDAD_R1;  AGE4YR = WEDA_R1; GENDER = SEXO; EDUC = C10R1; COG1=FINALSCR; COG2=WFINSCR; RACE=R2;
DISCRIM=R1; GDS1=DEPRE_Y; GDS2=WDEPRE_Y; SES_LAD=E3; SOC_SUP=M1O;

IF GENDER = 2 THEN FEM_GENDER = 1;
IF GENDER = 1 THEN FEM_GENDER = 0;

*HEALTH CONDITIONS;
DIAB=.;
IF G8 EQ 1 THEN DIAB=1;
IF G8 EQ 2 THEN DIAB=0;

HTN=.;
IF G4 EQ 1 THEN HTN=1;
IF G4 EQ 2 THEN HTN=0;

MI=.;
IF G35 EQ 1 THEN MI=1;
IF G35 EQ 2 THEN MI=0;

CHF=.;
IF G36 EQ 1 THEN CHF=1;
IF G36 EQ 2 THEN CHF=0;

STROKE=.;
IF G40 EQ 1 THEN STROKE=1;
IF G40 EQ 2 THEN STROKE=0;

*PAIN CONDITIONS;
PAINMED = .;
IF YWJ6M LT 0 THEN PAINMED = .;
ELSE IF YWJ6M = 1 THEN PAINMED = 1;
ELSE IF YWJ6M = 2 THEN PAINMED = 0;
*THIS IS BASED OFF OF WAVE 2 WHEN THE QUESTION WAS ASKED;
BODYPAIN1 = .;
IF G112 <1 OR G112 = . THEN BODYPAIN1 = 0;
IF G112 = 1 THEN BODYPAIN1 = 1;
IF G112 = 2 THEN BODYPAIN1 = 2;
IF G112 = 3 THEN BODYPAIN1 = 3;

BODYPAIN1_GMC = (BODYPAIN1 - MEAN(BODYPAIN1));

*JOINT PAIN;
JOINTPAIN = .;
IF G101 < 1 OR G101 = . THEN JOINTPAIN = 0;
IF G101 = 1 THEN JOINTPAIN = 1;
IF G101 = 2 THEN JOINTPAIN = 2;
IF G101 = 3 THEN JOINTPAIN = 3;
IF G101 = 3 THEN JOINTPAIN = 4;
IF G101 = 3 THEN JOINTPAIN = 5;
IF G101 = 3 THEN JOINTPAIN = 6;
IF G101 = 3 THEN JOINTPAIN = 7;
IF G101 = 3 THEN JOINTPAIN = 8;
IF G101 = 3 THEN JOINTPAIN = 9;
IF G101 = 3 THEN JOINTPAIN = 10;


BODYPAIN2 = .;
IF WG112 < 1 OR WG112 = . THEN BODYPAIN2 = 0;
IF WG112 = 1 THEN BODYPAIN2 = 1;
IF WG112 = 2 THEN BODYPAIN2 = 2;
IF WG112 = 3 THEN BODYPAIN2 = 3;
IF WG112 = 3 THEN BODYPAIN2 = 4;
IF WG112 = 3 THEN BODYPAIN2 = 5;
IF WG112 = 3 THEN BODYPAIN2 = 6;
IF WG112 = 3 THEN BODYPAIN2 = 7;
IF WG112 = 3 THEN BODYPAIN2 = 8;
IF WG112 = 3 THEN BODYPAIN2 = 9;
IF WG112 = 3 THEN BODYPAIN2 = 10;

BODYPAIN2C = .;
IF WG112 = 0 THEN BODYPAIN2C = 0;
IF WG112 IN(1-3) THEN BODYPAIN2C = 1;
IF WG112 IN(4-6) THEN BODYPAIN2C = 2;
IF WG112 IN(7-10) THEN BODYPAIN2C = 3;

BODYPAINCHANGE = BODYPAIN2C - BODYPAIN1;

PAINSTATUS1 = .;
IF G111 <1 THEN PAINSTATUS1= .;
IF G111 = 1 THEN PAINSTATUS1 = 1;
IF G111 = 2 THEN PAINSTATUS1 = 0;

PAINSTATUS2 = .;
IF WG111 <1 THEN PAINSTATUS2= .;
IF WG111 = 1 THEN PAINSTATUS2 = 1;
IF WG111 = 2 THEN PAINSTATUS2 = 0;

PAINSTATUSCHANGE = PAINSTATUS2 - PAINSTATUS1;

PAININTENSITY1 = .;
IF G111 = 2 THEN PAININTENSITY1 = 0;
IF G112 = 1 THEN PAININTENSITY1 = 1;
IF G112 = 2 THEN PAININTENSITY1 = 2;
IF G112 = 3 THEN PAININTENSITY1 = 3;

PAININTERFER1 = .;
IF G111 = 2 THEN PAININTERFER1  = 0;
IF G112 = 1 THEN PAININTERFER1  = 1;
IF G112 = 2 THEN PAININTERFER1  = 0;

PAININTERFER2 = .;
IF WG111 = 2 THEN PAININTERFER2  = 0;
IF WG112 = 1 THEN PAININTERFER2  = 1;
IF WG112 = 2 THEN PAININTERFER2  = 0;


CHRONICPAIN = .;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 1 THEN CHRONICPAIN = 1;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN CHRONICPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN CHRONICPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN CHRONICPAIN = 0;


NOVELPAIN = .;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN NOVELPAIN = 1;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN NOVELPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN NOVELPAIN = 0;

BACKPAINSCALE1 = . ;
IF G106 < 0 THEN BACKPAINSCALE1 = 0;
IF G101 = 1 THEN BACKPAINSCALE1 = 1;
IF G101 = 2 THEN BACKPAINSCALE1 = 2;
IF G101 = 3 THEN BACKPAINSCALE1 = 3;
IF G101 = 3 THEN BACKPAINSCALE1 = 4;
IF G101 = 3 THEN BACKPAINSCALE1 = 5;
IF G101 = 3 THEN BACKPAINSCALE1 = 6;
IF G101 = 3 THEN BACKPAINSCALE1 = 7;
IF G101 = 3 THEN BACKPAINSCALE1 = 8;
IF G101 = 3 THEN BACKPAINSCALE1 = 9;
IF G101 = 3 THEN BACKPAINSCALE1 = 10;

SEVEREBODYPAIN1 = .;
IF G112 <1 OR G112 = . THEN SEVEREBODYPAIN1 = 0;
IF G112 = 1 THEN SEVEREBODYPAIN1 = 0;
IF G112 = 2 THEN SEVEREBODYPAIN1 = 0;
IF G112 = 3 THEN SEVEREBODYPAIN1 = 1;

*SCI;
SCI1 = .;
IF G180 LE 0 THEN SCI1 = .;
IF G180 = 1 THEN SCI1 = 1;
IF G180 = 2 THEN SCI1 = 0;

SCI2 = .;
IF WG180 LE 0 THEN SCI2 = .;
IF WG180 = 1 THEN SCI2 = 1;
IF WG180 = 2 THEN SCI2 = 0;

SCICHANGE = SCI2 - SCI1;

SCI = .;
IF SCI1 = 1 OR SCI2 = 1 THEN SCI = 1;
IF SCI1 = 0 AND SCI2 = 0 THEN SCI = 0;

SCIONSET = .;
IF SCI1 = 0 AND SCI2 = 1 THEN SCIONSET = 1;
IF SCI1 = 1 AND SCI2 = 0 THEN SCIONSET = 0;
IF SCI1 = 1 AND SCI2 = 1 THEN SCIONSET = 0;

SCIREMISSION= .;
IF SCI1 = 0 AND SCI2 = 1 THEN SCIREMISSION = 0;
IF SCI1 = 1 AND SCI2 = 0 THEN SCIREMISSION = 1;
IF SCI1 = 1 AND SCI2 = 1 THEN SCIREMISSION = 0;

SCICONTINUED= .;
IF SCI1 = 0 AND SCI2 = 0 THEN SCICONTINUED = 0;
IF SCI1 = 0 AND SCI2 = 1 THEN SCICONTINUED = 0;
IF SCI1 = 1 AND SCI2 = 0 THEN SCICONTINUED = 0;
IF SCI1 = 1 AND SCI2 = 1 THEN SCICONTINUED = 1;

GDS1NOMEM = GDS1-SCI1;
GDS2NOMEM = GDS2-SCI2;

*INCLUSION VARIABLE FOR PAIN PAPER;

*CHILDHOOD VARS;
IF H14 LT 0 THEN H14=.;
CH_HEALTH=.; CH_HEALTH=H14;

DAD_READ=H2A; DAD_EDUC=H3A;
MOM_READ=H6A; MOM_EDUC=H6C;

DAD_READ=.;
IF H2A NE . THEN DO;
IF H2A EQ 1 THEN DAD_READ=1;
IF H2A EQ 2 THEN DAD_READ=0;
END;

MOM_READ=.;
IF H6A NE . THEN DO;
IF H6A EQ 1 THEN MOM_READ=1;
IF H6A EQ 2 THEN MOM_READ=0;
END;

CH_SES=.;
CH_SES=H1;

CH_ECON=.;
IF H2 NE . THEN DO;
IF H2 EQ 1 THEN CH_ECON=1;
IF H2 EQ 2 THEN CH_ECON=0;
END;

SCHOOL_WORK=.;
IF H8 NE . THEN DO;
IF H8 EQ 1 THEN SCHOOL_WORK=1;
IF H8 EQ 2 THEN SCHOOL_WORK=0;
END;

SCHOOL_HEALTH=.;
IF H15 NE . THEN DO;
IF H15 EQ 1 THEN SCHOOL_HEALTH=0;
IF H15 GE 2 THEN SCHOOL_HEALTH=1;
END;

CH_RURAL=.;
IF O2 NE . THEN DO;
CH_RURAL=0;
IF O2 EQ 1 THEN CH_RURAL=1;
END;

*LITERACY, DOC VISISTS, DIABETES MEDS OR SHOTS;
DOC_VISIT=.;
IF K25 LE 1 THEN DOC_VISIT=0;
IF K25 GT 1 THEN DOC_VISIT=1;

READ=.;
IF C8R1 NE . THEN DO;
IF C8R1 EQ 1 THEN READ=1;
IF C8R1 EQ 2 THEN READ=0;
END;
*1 MISSING READING W COG SCORE AND 2 YRS EDUC;
IF CASEID=41194210 THEN READ=0;

DIAB_MED=.;
IF G9 NE . THEN DO;
IF G9 EQ 1 THEN DIAB_MED=1;
IF G9 EQ 2 THEN DIAB_MED=0;
END;

DIAB_SHOT=.;
IF G10 NE . THEN DO;
IF G10 EQ 1 THEN DIAB_SHOT=1;
IF G10 EQ 2 THEN DIAB_SHOT=0;
END;

*1 IS GOOD FOR DIET AND CONTROL ONLY;
DIAB_DIET=.;
IF G11 NE . THEN DO;
IF G11 EQ 1 THEN DIAB_DIET=1;
IF G11 EQ 2 THEN DIAB_DIET=0;
END;

DIAB_CONTROL=.;
IF G12 NE . THEN DO;
IF G12 EQ 1 THEN DIAB_CONTROL=1;
IF G12 EQ 2 THEN DIAB_CONTROL=0;
END;

DIAB_DAILY=.;
IF G16 NE . THEN DO;
IF G16 EQ 1 THEN DIAB_DAILY=1;
IF G16 EQ 2 THEN DIAB_DAILY=0;
END;

DIAB_CIRC=.;
IF G17 NE . THEN DO;
IF G17 EQ 1 THEN DIAB_CIRC=1;
IF G17 EQ 2 THEN DIAB_CIRC=0;
END;

DIAB_VIS=.;
IF G18 NE . THEN DO;
IF G18 EQ 1 THEN DIAB_VIS=1;
IF G18 EQ 2 THEN DIAB_VIS=0;
END;

DIAB_FEET=.;
IF G19 NE . THEN DO;
IF G19 EQ 1 THEN DIAB_FEET=1;
IF G19 EQ 2 THEN DIAB_FEET=0;
END;

DIAB_AMP=.;
IF G20 NE . THEN DO;
IF G20 EQ 1 THEN DIAB_AMP=1;
IF G20 EQ 2 THEN DIAB_AMP=0;
END;

DIAB_KIDNEY=.;
IF G21 NE . THEN DO;
IF G21 EQ 1 THEN DIAB_KIDNEY=1;
IF G21 EQ 2 THEN DIAB_KIDNEY=0;
END;

FDIAB_CIRC=.;
IF YG17 NE . THEN DO;
IF YG17 EQ 1 THEN FDIAB_CIRC=1;
IF YG17 EQ 2 THEN FDIAB_CIRC=0;
END;

FDIAB_VIS=.;
IF YG18 NE . THEN DO;
IF YG18 EQ 1 THEN FDIAB_VIS=1;
IF YG18 EQ 2 THEN FDIAB_VIS=0;
END;

FDIAB_FEET=.;
IF YG19 NE . THEN DO;
IF YG19 EQ 1 THEN FDIAB_FEET=1;
IF YG19 EQ 2 THEN FDIAB_FEET=0;
END;

FDIAB_AMP=.;
IF YG20 NE . THEN DO;
IF YG20 EQ 1 THEN FDIAB_AMP=1;
IF YG20 EQ 2 THEN FDIAB_AMP=0;
END;

FDIAB_KIDNEY=.;
IF YG21 NE . THEN DO;
IF YG21 EQ 1 THEN FDIAB_KIDNEY=1;
IF YG21 EQ 2 THEN FDIAB_KIDNEY=0;
END;
*RACE1=BLACK, RACE2=MIXED, RACE3=WHITE, RACE4=INDIAN OR OTHER (RECODED BELOW);
*PROXY DID NOT REPORT RACE;
IF R2 NE . THEN DO;
RACE1=0; RACE2=0; RACE3=0; RACE4=0;
IF RACE=1 THEN RACE1=1;
IF RACE=2 THEN RACE2=1;
IF RACE=3 THEN RACE3=1;
IF RACE=4 THEN RACE4=1;
IF RACE=5 THEN RACE4=1;
END;

W_RACE=.;
IF R2 NE . THEN DO;
IF RACE=3 THEN W_RACE=1;
ELSE W_RACE=0;
END;

IF SES_LAD GT 10 THEN SES_LAD=.;

*DEPRESSIVE SX, DEP1 IS GE 5, DEP2 GE 9 (MODERATE OR SEVERE);
IF GDS1=99 THEN GDS1=.;
IF GDS2=99 THEN GDS2=.;

*ORDINAL DEPRESSION GDS;
DEP1=.;
IF GDS1 NE . THEN DO;
IF GDS1 LT 5 THEN DEP1=0;
IF GDS1 GE 5 AND GDS1 LT 9 THEN DEP1=1;
IF GDS1 GE 9 AND GDS1 LT 12 THEN DEP1=2;
IF GDS1 GE 12 THEN DEP1=3;
END;
DEP2=.;
IF GDS2 NE . THEN DO;
IF GDS2 LT 5 THEN DEP2=0;
IF GDS2 GE 5 AND GDS2 LT 9 THEN DEP2=1;
IF GDS2 GE 9 AND GDS2 LT 12 THEN DEP2=2;
IF GDS2 GE 12 THEN DEP2=3;
END;

*TEETH;
TEETH_PROB=.;
IF G126 NE . THEN DO;
IF G126=5 THEN TEETH_PROB=0;
IF G126=1 THEN TEETH_PROB=1;
IF G126 GE 2 THEN TEETH_PROB=2;
END;

ALONE = .;
IF C1NUM EQ 0 THEN ALONE =0;
IF C1NUM EQ 1 THEN ALONE = 0;
IF C1NUM EQ 2 THEN ALONE = 1;
IF C1NUM EQ 3 THEN ALONE = 1;
IF C1NUM EQ 4 THEN ALONE = 1;
IF C1NUM EQ 5 THEN ALONE = 1;
IF C1NUM EQ 6 THEN ALONE = 1;
IF C1NUM EQ 7 THEN ALONE = 1;
IF C1NUM EQ 8 THEN ALONE = 1;
IF C1NUM EQ 9 THEN ALONE = 1;
IF C1NUM EQ 10 THEN ALONE = 1;
*MARITAL;
MARITAL = .;
IF MARI_R1 = 1 THEN MARITAL = 1;
IF MARI_R1 = 2 THEN MARITAL = 1;
IF MARI_R1 GT 2 THEN MARTIAL = 0;
*ORDINAL CATEGORIES WITH MISSING FOR PARENT EDUC (1=DON'T KNOW);
MOM_EDUC0=0; MOM_EDUC1=0; MOM_EDUC2=0; MOM_EDUC3=0;
IF MOM_EDUC=. THEN MOM_EDUC0=1;
IF MOM_EDUC=0 THEN MOM_EDUC1=1;
IF MOM_EDUC=1 THEN MOM_EDUC2=1;
IF MOM_EDUC=2 THEN MOM_EDUC3=1;
DAD_EDUC0=0; DAD_EDUC1=0; DAD_EDUC2=0; DAD_EDUC3=0;
IF DAD_EDUC=. THEN DAD_EDUC0=1;
IF DAD_EDUC=0 THEN DAD_EDUC1=1;
IF DAD_EDUC=1 THEN DAD_EDUC2=1;
IF DAD_EDUC=2 THEN DAD_EDUC3=1;
*TURN MISSING RACE TO "OTHER" CATEGORY WRONG BECAUSE IF IMPAIRED
PROXY DID NOT REPORT RACE;
IF RACE=. THEN RACE=5;
IF RACE=5 THEN RACE1=0;
IF RACE=5 THEN RACE2=0;
IF RACE=5 THEN RACE3=0;
IF RACE=5 THEN RACE4=1;


*ADULT SES;
PAY_LIVING=.; PAY_HEALTH=.;
IF N71 NE . THEN DO;
IF N71=1 THEN PAY_LIVING=1;
IF N71 GT 1 THEN PAY_LIVING=0;
END;
IF N72 NE . THEN DO;
IF N72=1 THEN PAY_HEALTH=1;
IF N72 GT 1 THEN PAY_HEALTH=0;
END;
PAY_EITHER=.;
IF PAY_LIVING NE . OR PAY_HEALTH NE . THEN DO;
PAY_EITHER=0;
IF PAY_LIVING=1 THEN PAY_EITHER=1;
IF PAY_HEALTH=1 THEN PAY_EITHER=1;
END;

ALL_DATA=0;
IF (COG1 NE . AND EDUC NE . AND CH_HEALTH NE . AND CH_SES NE . AND PAY_EITHER NE .
AND CH_RURAL NE . AND CH_ECON NE .) THEN ALL_DATA=1;
RUN;

*GET SAMPLE BEFORE DELETING THOSE W MISSING EDUC OR COG FXN HERE;
*FIGURE OUT WHICH CHILDHOOD VARS MOST COMPLETE;
PROC FREQ;
WHERE COG1 NE . AND EDUC NE . AND CH_HEALTH NE . AND CH_SES NE . AND PAY_EITHER NE .
AND CH_RURAL NE . AND CH_ECON NE .;
TABLES FEM_GENDER RACE SCHOOL_HEALTH SCHOOL_WORK CH_HEALTH
MOM_READ MOM_EDUC DAD_READ DAD_EDUC CH_SES CH_ECON CH_RURAL RACE N71 N72;
RUN;

PROC FREQ;
WHERE COG1 NE . AND EDUC NE .;
TABLES COG1 PROXY PRXYRL_1;
RUN;

DATA FIVE;
SET FOUR;

IF EDUC=. THEN DELETE;
IF COG1=. THEN DELETE;

*RECODE EDUC OF 'OTHER';
IF EDUC = 17 THEN DO;
EDUC=14;
END;

*CONTINUOUS EDUCATION;
EDUC_C=EDUC;
IF EDUC GT 12 THEN DO;
IF EDUC EQ 13 THEN EDUC_C=14;
IF EDUC EQ 14 THEN EDUC_C=13;
IF EDUC EQ 15 THEN EDUC_C=16;
IF EDUC EQ 16 THEN EDUC_C=18;
END;

*EDUCATION 5-LEVEL CATEGORIES;
IF EDUC NE . THEN DO;
EDUC1=0; EDUC2=0; EDUC3=0; EDUC4=0; EDUC5=0;
IF EDUC_C LE 3 THEN EDUC1=1;
IF EDUC_C GT 3 AND EDUC_C LT 8 THEN EDUC2=1;
IF EDUC_C GT 7 AND EDUC_C LT 12 THEN EDUC3=1;
IF EDUC_C GT 11 AND EDUC_C LT 13 THEN EDUC4=1;
IF EDUC_C GE 13 THEN EDUC5=1;
END;

*AGE CATEGORIES;
IF AGE NE . THEN DO;
AGE1=0; AGE2=0; AGE3=0; AGE4=0;
IF AGE LE 69 THEN AGE1=1;
IF AGE GT 69 AND AGE LT 76 THEN AGE2=1;
IF AGE GT 75 AND AGE LT 81 THEN AGE3=1;
IF AGE GE 81 THEN AGE4=1;
END;

IF AGE NE . THEN DO;
AGE1R=0; AGE2R=0; AGE3R=0; AGE4R=0; AGE5R=0;
IF AGE LE 64 THEN AGE1R=1;
IF AGE GT 64 AND AGE LT 70 THEN AGE2R=1;
IF AGE GT 69 AND AGE LT 76 THEN AGE3R=1;
IF AGE GT 75 AND AGE LT 81 THEN AGE4R=1;
IF AGE GT 80 THEN AGE5R=1;
END;
*NUMBER IN HOME;
NUMBERHH = .;
NUMBERHH = C1NUM;

*ALONE;


*COGNITIVE DECLINE;
IF COG2 NE . THEN DO;
COGD=COG1-COG2;
END;


RUN;

/*MODEL FOR REGRESSION BASED CUTOFFS AT BASELINE--HS/VOCATIONAL EDUC IS REF
AND AGE 60-64 IS REF GROUP;
* R-SQUARE FOR CATEGORICAL VS CONTINUOUS IS SIMILAR;
PROC REG DATA=FIVE;
   MODEL COG1 = AGE2 AGE3 AGE4 EDUC1 EDUC2 EDUC3 EDUC4 FEM_GENDER READ/STB RSQUARE;
RUN;
PROC REG;
   MODEL COG1 = AGE EDUC_C FEM_GENDER READ/STB RSQUARE;
RUN;
*MODEL FOR REGRESSION BASED CUTOFFS FOR DECLINE??;
PROC REG;
   MODEL COGD = COG1 AGE EDUC_C FEM_GENDER READ/STB RSQUARE;
RUN; */

DATA SIX;
SET FIVE;

*DIABETES AGE OF ONSET MISSING FOR SOME, USING CURRENT AGE;
IF COG1 NE . AND DIAB=1 AND G8AEDAD=. THEN DO;
G8AEDAD=AGE;
END;

YRSDIAB=.;
YRSDIAB=AGE-G8AEDAD;
IF G8AEDAD EQ . THEN YRSDIAB=0;

IF DIAB=0 THEN EARLY_DIAB=0;
IF DIAB=0 THEN LATE_DIAB=0;

IF DIAB=1 THEN DO;
IF G8AEDAD GE 30 THEN LATE_DIAB=1;
IF G8AEDAD LT 30 THEN LATE_DIAB=0;
IF G8AEDAD GE 30 THEN EARLY_DIAB=0;
IF G8AEDAD LT 30 THEN EARLY_DIAB=1;
END;

DIAB_COMP=.;
DIAB_COMP=(DIAB_CIRC + DIAB_VIS + DIAB_FEET + DIAB_AMP + DIAB_KIDNEY);

DIAB_COMP2=.;
DIAB_COMP2=(FDIAB_CIRC + FDIAB_VIS + FDIAB_FEET + FDIAB_AMP + FDIAB_KIDNEY);

VASC_COMP=.;
VASC_COMP=(HTN + MI + CHF + STROKE);

VASC_COMP2=.;
VASC_COMP2=(DIAB + HTN + MI + CHF + STROKE);

DIVASC_COMP=.;
IF VASC_COMP GE 1 THEN DIVASC_COMP=1;
IF VASC_COMP LT 1 THEN DIVASC_COMP=0;

*REGRESSION BASED CUTOFFS FOR BASELINE IMPAIRMENT;
*BASED ON AGE, EDUCATION LEVEL, AND READING ON BASELINE COG MEASURES;
*WG8AE = FOLLOW UP AGE;

EXP_COG=.;
IF COG1 NE . THEN DO;
EXP_COG = 19.23297 + (-0.07861*AGE) + (0.14672*EDUC_C) + (0.27432*FEM_GENDER)
+ (1.41472*READ);
END;
INCIDENT_DEP = .;
IF GDS2 = . THEN INCIDENT_DEP = .;
IF GDS2 LT 5 THEN INCIDENT_DEP = 0;
IF GDS2 GT 4 THEN INCIDENT_DEP = 1;
COGDCAT=.;
IF COGD EQ . THEN COGDCAT = .;
IF COGD LT 1 THEN COGDCAT =0;
IF COGD EQ 1 THEN COGDCAT =1;
IF COGD EQ 2 THEN COGDCAT = 2;
IF COGD EQ 3 THEN COGDCAT = 3;
IF COGD EQ 4 THEN COGDCAT =4;
IF COGD EQ 5 THEN COGDCAT =5;
IF COGD EQ 6 THEN COGDCAT =6;
IF COGD EQ 7 THEN COGDCAT = 7;
IF COGD EQ 8 THEN COGDCAT =8;
IF COGD EQ 9 THEN COGDCAT = 9;
IF COGD EQ 10 THEN COGDCAT =10;
IF COGD EQ 11 THEN COGDCAT = 11;


COGDBIN = .;
IF COGDCAT = 0 THEN COGDBIN = 0;
IF COGDCAT >0 THEN COGDBIN = 1;


*USE AGE AT FOLLOW UP FOR INCIDENT IMPAIRMENT;
EXP_COG2=.;
EXP_COG2 = 19.23297 + (-0.07861*AGE4YR) + (0.14649*EDUC_C)  + (0.27432*FEM_GENDER)
+ (1.41472*READ);

IF COG1=. THEN EXP_COG=.;
IF COG1=. THEN EXP_COG2=.;
IF COG2=. THEN EXP_COG2=.;

COGDIFF=.;
COGDIFF=EXP_COG-COG1;

COGDIFF2=.;
COGDIFF2=EXP_COG2-COG2;

*IMPAIRMENT DEFINED BY 1.5 SD BELOW DIFFERENCE BETWEEN OBS AND EXPECTED SCORE;
*USED SD FOR COGDIFF OF 2.73 (OTHER OPTION IS TO USE SD FOR EXP_COG);
COG_IMP=.;
IF EXP_COG NE . THEN DO;
IF COGDIFF GE 4 THEN COG_IMP=1;
ELSE COG_IMP=0;
END;

COG_IMP2=.;
IF COG1 NE . AND COG2 NE . THEN DO;
IF COGDIFF2 GE 4 THEN COG_IMP2=1;
ELSE COG_IMP2=0;
END;

*CABAN CUT SCORE OF LE 10;
CI_CABAN=.;
IF COG1 NE . THEN DO;
IF COG1 GT 10 THEN CI_CABAN=0;
IF COG1 LE 10 THEN CI_CABAN=1;
END;

CDCAT = .;
IF COGDCAT NE . THEN DO;
IF COGDCAT GE 1 THEN CDCAT = 1;
IF COGDCAT LT 1 THEN CDCAT = 0;
END;

CI_CABAN2=.;
IF COG2 NE . THEN DO;
IF COG2 GT 10 THEN CI_CABAN2=0;
IF COG2 LE 10 THEN CI_CABAN2=1;
END;

*INCIDENT DEPRESSION= HIGHER CATEGORY ON ORDINAL SCALE AT FOLLOW UP;
DEPI=.;
IF DEP1 NE . AND DEP2 NE . THEN DO;
IF DEP2 GT DEP1 THEN DEPI=1;
ELSE DEPI=0;
END;

*COMORBID DEPRESSION AND COG IMP;
CO_MORB1=.;
IF COG_IMP NE . AND DIDEP1 NE . THEN DO;
IF COG_IMP=1 AND DIDEP1=1 THEN CO_MORB1=1;
ELSE CO_MORB1=0;
END;
BASELINE_DEP = .;
IF GDS1 NE . THEN DO;
IF GDS1 <5 THEN BASELINE_DEP = 0;
IF GDS1 GE 5 THEN BASELINE_DEP = 1;
END;

CO_MORB2=.;
IF COG_IMP2 NE . AND DIDEP2 NE . THEN DO;
IF COG_IMP2=1 AND DIDEP2=1 THEN CO_MORB2=1;
ELSE CO_MORB2=0;
END;

*FOLLOW UP TIME;
FU=.;
IF AGE2 NE . THEN DO;
FU=AGE2-AGE;
END;
*OCCUPATION: CODE_N18 IF MAIN JOB WAS ALSO LAST JOB, CODE_N25 IF NOT;
OCC_CODE=.;
OCC_CODE=CODE_N25;
IF CODE_N25=. THEN OCC_CODE=CODE_N18;
*GET RID OF COGNITIVE CHANGE OUTLIERS (3.5 SD GREATER THAN CHANGE)?;
*IF COGD GT 10.405 THEN COG_IMP2 = .;
*IF COGD LT -9.624 THEN COG_IMP2 = .;
RUN;

DATA SEVEN;
SET SEVEN;
PAINSTATUSB = PAINSTATUS2-PAINSTATUS1;
SCIB = SCI2-SCI1;
BODYPAINB = BODYPAIN2C - BODYPAIN1;
GDSNOMEM = GDS2NOMEM - GDS1NOMEM;
RUN;
PROC MIXED DATA = SIX COVTEST METHOD = ML;
CLASS GENDER;
MODEL COGDCAT = PAINSTATUSB AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM PAINSTATUSB/SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA = SIX COVTEST METHOD = REML;
CLASS GENDER;
MODEL COGDCAT = PAINSTATUSB AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM PAINSTATUSB/SUB=CASEID TYPE=VC;
RUN;


PROC MIXED DATA = SIX COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER;
MODEL COG2 = COG1 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = SEVEN COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER;
MODEL COG2 = COG1 AGE /SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = SEVEN COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER;
MODEL COG2 = AGE COG1 GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM COG1 /SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = SEVEN COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER;
MODEL COG2 = COG1 PAINSTATUS1 SCI AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = EIGHT COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER CHRONICPAIN(REF = "0") NOVELPAIN(REF = "0") REMISSEDPAIN(REF = "0") ;
MODEL COGDCAT = COG1 CHRONICPAIN NOVELPAIN REMISSEDPAIN SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = HOME.SEVEN COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER;
MODEL COG2 = COG1 PAINSTATUSB SCIB AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = SIX COVTEST METHOD = REML;
WHERE  COG1 NE . AND CI_CABAN NE 1 AND GDS1NOMEM NE . AND GDS1NOMEM NE 99 AND AGE NE . AND GENDER NE . AND EDUC NE . AND COG2 NE . AND CI_CABAN2 NE 1 AND DIAB NE . AND VASC_COMP NE .;
CLASS GENDER;
MODEL COG2 =  PAINSTATUS1 SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM COG1 /SUB=CASEID TYPE=VC;
RUN;

PROC GLIMMIX DATA = EIGHT;
CLASS GENDER;
MODEL SCIONSET = CHRONICPAIN REMISSEDPAIN NOVELPAIN AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP;
RANDOM PAINSTATUSB /SUB=CASEID TYPE=VC;
ESTIMATE "NOVEL" NOVELPAIN 1;
ESTIMATE "REMISSED" REMISSEDPAIN 1;
ESTIMATE "CHRONIC" CHRONICPAIN 1;
RUN;

PROC FREQ DATA = EIGHT;
TABLE NOVELPAIN REMISSEDPAIN CHRONICPAIN;
RUN;

DATA EIGHT;
SET HOME.SEVEN;
RUN;

DATA HOME.EIGHT;
SET HOME.SEVEN;
SCICONTINUED= .;
IF SCI1 = 0 AND SCI2 = 0 THEN SCICONTINUED = 0;
ELSE IF SCI1 = 0 AND SCI2 = 1 THEN SCICONTINUED = 0;
ELSE IF SCI1 = 1 AND SCI2 = 0 THEN SCICONTINUED = 0;
ELSE IF SCI1 = 1 AND SCI2 = 1 THEN SCICONTINUED = 1;
CHRONICPAIN = .;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 1 THEN CHRONICPAIN = 1;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN CHRONICPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN CHRONICPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN CHRONICPAIN = 0;

NOVELPAIN = .;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN NOVELPAIN = 1;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN NOVELPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN NOVELPAIN = 0;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 1 THEN NOVELPAIN = 0;

REMISSEDPAIN = .;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN REMISSEDPAIN = 0;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN REMISSEDPAIN = 1;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN REMISSEDPAIN = 0;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 1 THEN REMISSEDPAIN = 0;

NOPAIN = .;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN NOPAIN = 0;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN NOPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN NOPAIN = 1;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 1 THEN NOPAIN = 0;
RUN;

*CRITERIA FOR INCLUDE VARIABLE: WHERE  COG1 NE . AND CI_CABAN NE 1 AND GDS1NOMEM NE . AND GDS1NOMEM NE 99 AND AGE NE . AND GENDER NE . AND EDUC NE . AND COG2 NE . AND CI_CABAN2 NE 1 AND DIAB NE . AND VASC_COMP NE .;
DATA HOME.EIGHT;
SET HOME.EIGHT;
INCLUDE = .;
IF CASEID IN();


*DATA CONVERTED TO LONG FOR CONCURRENT ANALYSES (NINELONG);

*DESCRIPTIVES;

*PAIN CHANGES ACROSS TIME;
PROC FREQ DATA = EIGHT;
TABLE NOVELPAIN REMISSEDPAIN CHRONICPAIN;
RUN;

*FREQUENCIES ACROSS ALL BASELINE DATA;
PROC FREQ DATA= HOME.NINELONG  DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
TABLE PAINSTATUS GDSNOMEM GENDER EDUC AGE DIAB VASC_COMP;
RUN;

*CONTINUOUS DESCRIPTIVES ACROSS ALL BASELINE DATA;
PROC MEANS DATA= HOME.NINELONG N MEAN STD RANGE;
WHERE INCLUDE = 1 AND INDEX1 = 1;
VAR COG GDSNOMEM AGE EDUC VASC_COMP;
RUN;

*FREQUENCIES ACROSS BASELINE DATA FOR PEOPLE WITH PAIN;
PROC FREQ DATA= HOME.NINELONG ;
WHERE INCLUDE = 1 AND INDEX1 = 1 AND PAINSTATUS = 1;
TABLE GDSNOMEM GENDER EDUC AGE DIAB VASC_COMP GDSNOMEM;
RUN;

*FREQUENCIES ACROSS BASELINE DATA FOR PEOPLE WITHOUT PAIN;
PROC FREQ DATA= HOME.NINELONG ;
WHERE INCLUDE = 1 AND INDEX1 = 1 AND PAINSTATUS = 0;
TABLE GDSNOMEM GENDER EDUC AGE DIAB VASC_COMP;
RUN;

*CONTINUOUS BASELINE DESCRIPTIVES FOR PEOPLE WITH PAIN;
PROC MEANS DATA= HOME.NINELONG  N MEAN STD RANGE;
WHERE INCLUDE = 1 AND INDEX1 = 1 AND PAINSTATUS = 1;
VAR COG GDSNOMEM AGE EDUC VASC_COMP;
RUN;

*CONTINUOUS BASELINE DESCRIPTIVES FOR PEOPLE WITHOUT PAIN;
PROC MEANS DATA= HOME.NINELONG  N MEAN STD RANGE;
WHERE INCLUDE = 1 AND INDEX1 = 1 AND PAINSTATUS = 0;
VAR COG GDSNOMEM AGE EDUC VASC_COMP;
RUN;

*CORRELATIONS BETWEEN BASELINE VARIABLES FORTHE FULL SAMPLE;
PROC CORR DATA= HOME.SEVEN KENDALL;
WHERE INCLUDE = 1;
VAR PAINSTATUS1 SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP;
RUN;

PROC CORR DATA= HOME.NINELONG KENDALL;
WHERE INCLUDE = 1 AND INDEX1 = 1;
VAR PAINSTATUS SCI AGE GDSNOMEM GENDER EDUC DIAB VASC_COMP;
RUN;

*DESCRIPTIVE TESTING;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR COG;
RUN;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR SCI;
RUN;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR GDSNOMEM;
RUN;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR AGE;
RUN;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR EDUC;
RUN;
PROC FREQ DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
TABLES PAINSTATUS*GENDER / CHISQ;
RUN;
PROC FREQ DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
TABLES PAINSTATUS*DIAB / CHISQ;
RUN;
PROC FREQ DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
TABLES PAINSTATUS*VASC_COMP / CHISQ;
RUN;
PROC FREQ DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
TABLES PAINSTATUS*SCI / CHISQ;
RUN;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR VASC_COMP;
RUN;

LIBNAME HOME 'L:\PREHCO PAPER';
RUN;

*COGNITIVE DECLINE ANALYSES;

PROC MIXED DATA = HOME.EIGHT NOCLPRINT COVTEST METHOD = REML;
WHERE INCLUDE = 1;
MODEL COGDCAT = / SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT /SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA = HOME.EIGHT NOCLPRINT COVTEST METHOD = REML;
WHERE INCLUDE = 1;
MODEL COGDCAT = AGE / SOLUTION DDFM=BETWITHIN;
REPEATED /SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA = HOME.EIGHT NOCLPRINT COVTEST METHOD = REML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0");
MODEL COGDCAT = COG1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP / SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA = HOME.EIGHT NOCLPRINT COVTEST METHOD = REML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0") CHRONICPAIN (REF="0") REMISSEDPAIN (REF="0") NOVELPAIN (REF="0") SCI1 (REF="0");
MODEL COGDCAT = COG1 CHRONICPAIN REMISSEDPAIN NOVELPAIN SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP / SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
ESTIMATE "NOVEL" NOVELPAIN 1;
ESTIMATE "REMISSED" REMISSEDPAIN 1;
ESTIMATE "CHRONIC" CHRONICPAIN 1;
RUN;


PROC MIXED DATA = HOME.EIGHT NOCLPRINT COVTEST METHOD = REML;
CLASS GENDER;
MODEL COGDCAT = COG1 CHRONICPAIN REMISSEDPAIN NOVELPAIN SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP / SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT /SUB=CASEID TYPE=VC;
ESTIMATE "NOVEL" NOVELPAIN 1;
ESTIMATE "REMISSED" REMISSEDPAIN 1;
ESTIMATE "CHRONIC" CHRONICPAIN 1;
RUN;

*CONCURRENT COGNITION ANALYSES;
*MLM ANALYSIS;
*UNCONDITIONAL MEANS MODEL;
PROC MIXED DATA=  HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE  INCLUDE = 1;
MODEL COG= /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;

*UNCONDITIONAL GROWTH MODEL;
PROC MIXED DATA= HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE INCLUDE = 1;
CLASS GENDER;
MODEL COG= AGE /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;
*CONDITIONAL MEANS MODEL;
PROC MIXED DATA= HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0");
MODEL COG= AGE GDSNOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;

*MAIN CONDITIONAL GROWTH MODEL;
PROC MIXED DATA= HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0") PAINSTATUS (REF="0");
MODEL COG= AGE PAINSTATUS GDSNOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA= HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0") PAINSTATUS (REF="0") SCI (REF="0");
MODEL COG= AGE PAINSTATUS SCI GDSNOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;

*MODEL USED TO MEDIATION PROCEDURES;
PROC GLIMMIX DATA= HOME.NINELONG;
WHERE INCLUDE = 1;
MODEL SCI = AGE COG PAINSTATUS GDSNOMEM GENDER EDUC DIAB VASC_COMP /DIST=BINARY LINK=LOGIT DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE = VC;
RUN;
*HTTP://QUANTPSY.ORG/SOBEL/SOBEL.HTM*
************;
LIBNAME SASDATA 'L:\PREHCO PAPER' ;
RUN;

DATA ONE; SET SASDATA.PREHCO_WAVE1;
RUN;
PROC SORT; BY CASEID;
RUN;
DATA TWO; SET SASDATA.PREHCO_WAVE2;
RUN;
PROC SORT; BY CASEID;
RUN;
DATA THREE;
MERGE ONE (IN=A) TWO (IN=B); BY CASEID;
RUN;

DATA FOUR;
SET THREE;
*NUMBER IN HOUSEHOLD;
IF C1NUM LT 0 THEN C1NUM =.;
IF FINALSCR LT 0 THEN FINALSCR =.;
IF WFINSCR LT 0 THEN WFINSCR =.;
*AGE;
IF EDAD_R1 LT 0 THEN EDAD_R1 =.;
IF WEDA_R1 LT 0 THEN WEDA_R1 =.;
IF C8R1 LT 0 THEN C8R1 =.;
IF C10R1 LT 0 THEN C10R1 =.;
*GDS;
IF DEPRE_Y LT 0 THEN DEPRE_Y = A;
IF WDEPRE_Y LT 0 THEN WDEPRE_Y =.;
IF E3 LT 0 THEN E3 =.;
*HEALTH CONDITIONS CODED NO IF IDK;
IF G4 LT 0 THEN G4 =2;
IF G8 LT 0 THEN G8 =2;
IF G35 LT 0 THEN G35 =2;
IF G36 LT 0 THEN G36 =2;
IF G40 LT 0 THEN G40 =2;
IF RBMI LT 0 THEN RBMI=.;
*AGE DIABETES ONSET;
IF G8AEDAD LT 0 THEN G8AEDAD =.;
IF G9 LT 0 THEN G9 =2;
*CODE DIABETES BEHAVIORS AS "NO" FOR PEOPLE MISSING CUZ DON'T HAVE DIABETES;
IF G10 LT 0 THEN G10 =2;
IF G11 LT 0 THEN G11 =2;
IF G12 LT 0 THEN G12 =1;
IF G13 LT 0 THEN G13 =2;
IF G14 LT 0 THEN G14 =.;
IF G15 LT 0 THEN G15 =.;
IF G16 LT 0 THEN G16 =2;
IF G17 LT 0 THEN G17 =2;
IF G18 LT 0 THEN G18 =2;
IF G19 LT 0 THEN G19 =2;
IF G20 LT 0 THEN G20 =2;
IF G21 LT 0 THEN G21 =2;

*CHILDHOOD CONDITIONS;
IF H2A LT 0 THEN H2A =.;
IF H3A LT 0 THEN H3A =.;
IF H6A LT 0 THEN H6A =.;
IF H6C LT 0 THEN H6C =.;
IF H8 LT 0 THEN H8=.;
IF H15 LT 0 THEN H15=.;
IF H1 LT 0 THEN H1=.;
IF H2 LT 0 THEN H2=.;
IF O2 LT 0 THEN O2=.;

IF K25 LT 0 THEN K25 =.;
IF M1O LT 0 THEN M1O =.;
IF R2 LT 0 THEN R2 =.;
IF R1 LT 0 THEN R1 =.;
IF C8R1 LT 0 THEN C8R1 =.;
IF J12 LT 0 THEN J12 =.;
IF G126 LT 0 THEN G126=.;
*KNEE HEIGHT;
IF U5_P LT 0 THEN U5_P=.;

*ADULT SES;
IF N71 LT 0 THEN N71=.;
IF N72 LT 0 THEN N72=.;

AGE = EDAD_R1;  AGE4YR = WEDA_R1; GENDER = SEXO; EDUC = C10R1; COG1=FINALSCR; COG2=WFINSCR; RACE=R2;
DISCRIM=R1; GDS1=DEPRE_Y; GDS2=WDEPRE_Y; SES_LAD=E3; SOC_SUP=M1O;

IF GENDER = 2 THEN FEM_GENDER = 1;
IF GENDER = 1 THEN FEM_GENDER = 0;

*HEALTH CONDITIONS;
DIAB=.;
IF G8 EQ 1 THEN DIAB=1;
IF G8 EQ 2 THEN DIAB=0;

HTN=.;
IF G4 EQ 1 THEN HTN=1;
IF G4 EQ 2 THEN HTN=0;

MI=.;
IF G35 EQ 1 THEN MI=1;
IF G35 EQ 2 THEN MI=0;

CHF=.;
IF G36 EQ 1 THEN CHF=1;
IF G36 EQ 2 THEN CHF=0;

STROKE=.;
IF G40 EQ 1 THEN STROKE=1;
IF G40 EQ 2 THEN STROKE=0;

*PAIN CONDITIONS;
PAINMED = .;
IF YWJ6M LT 0 THEN PAINMED = .;
ELSE IF YWJ6M = 1 THEN PAINMED = 1;
ELSE IF YWJ6M = 2 THEN PAINMED = 0;
*THIS IS BASED OFF OF WAVE 2 WHEN THE QUESTION WAS ASKED;
BODYPAIN1 = .;
IF G112 <1 OR G112 = . THEN BODYPAIN1 = 0;
IF G112 = 1 THEN BODYPAIN1 = 1;
IF G112 = 2 THEN BODYPAIN1 = 2;
IF G112 = 3 THEN BODYPAIN1 = 3;

BODYPAIN1_GMC = (BODYPAIN1 - MEAN(BODYPAIN1));

*JOINT PAIN;
JOINTPAIN = .;
IF G101 < 1 OR G101 = . THEN JOINTPAIN = 0;
IF G101 = 1 THEN JOINTPAIN = 1;
IF G101 = 2 THEN JOINTPAIN = 2;
IF G101 = 3 THEN JOINTPAIN = 3;
IF G101 = 3 THEN JOINTPAIN = 4;
IF G101 = 3 THEN JOINTPAIN = 5;
IF G101 = 3 THEN JOINTPAIN = 6;
IF G101 = 3 THEN JOINTPAIN = 7;
IF G101 = 3 THEN JOINTPAIN = 8;
IF G101 = 3 THEN JOINTPAIN = 9;
IF G101 = 3 THEN JOINTPAIN = 10;


BODYPAIN2 = .;
IF WG112 < 1 OR WG112 = . THEN BODYPAIN2 = 0;
IF WG112 = 1 THEN BODYPAIN2 = 1;
IF WG112 = 2 THEN BODYPAIN2 = 2;
IF WG112 = 3 THEN BODYPAIN2 = 3;
IF WG112 = 3 THEN BODYPAIN2 = 4;
IF WG112 = 3 THEN BODYPAIN2 = 5;
IF WG112 = 3 THEN BODYPAIN2 = 6;
IF WG112 = 3 THEN BODYPAIN2 = 7;
IF WG112 = 3 THEN BODYPAIN2 = 8;
IF WG112 = 3 THEN BODYPAIN2 = 9;
IF WG112 = 3 THEN BODYPAIN2 = 10;

BODYPAIN2C = .;
IF WG112 = 0 THEN BODYPAIN2C = 0;
IF WG112 IN(1-3) THEN BODYPAIN2C = 1;
IF WG112 IN(4-6) THEN BODYPAIN2C = 2;
IF WG112 IN(7-10) THEN BODYPAIN2C = 3;

BODYPAINCHANGE = BODYPAIN2C - BODYPAIN1;

PAINSTATUS1 = .;
IF G111 <1 THEN PAINSTATUS1= .;
IF G111 = 1 THEN PAINSTATUS1 = 1;
IF G111 = 2 THEN PAINSTATUS1 = 0;

PAINSTATUS2 = .;
IF WG111 <1 THEN PAINSTATUS2= .;
IF WG111 = 1 THEN PAINSTATUS2 = 1;
IF WG111 = 2 THEN PAINSTATUS2 = 0;

PAINSTATUSCHANGE = PAINSTATUS2 - PAINSTATUS1;

PAININTENSITY1 = .;
IF G111 = 2 THEN PAININTENSITY1 = 0;
IF G112 = 1 THEN PAININTENSITY1 = 1;
IF G112 = 2 THEN PAININTENSITY1 = 2;
IF G112 = 3 THEN PAININTENSITY1 = 3;

PAININTERFER1 = .;
IF G111 = 2 THEN PAININTERFER1  = 0;
IF G112 = 1 THEN PAININTERFER1  = 1;
IF G112 = 2 THEN PAININTERFER1  = 0;

PAININTERFER2 = .;
IF WG111 = 2 THEN PAININTERFER2  = 0;
IF WG112 = 1 THEN PAININTERFER2  = 1;
IF WG112 = 2 THEN PAININTERFER2  = 0;


CHRONICPAIN = .;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 1 THEN CHRONICPAIN = 1;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN CHRONICPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN CHRONICPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN CHRONICPAIN = 0;


NOVELPAIN = .;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN NOVELPAIN = 1;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN NOVELPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN NOVELPAIN = 0;

BACKPAINSCALE1 = . ;
IF G106 < 0 THEN BACKPAINSCALE1 = 0;
IF G101 = 1 THEN BACKPAINSCALE1 = 1;
IF G101 = 2 THEN BACKPAINSCALE1 = 2;
IF G101 = 3 THEN BACKPAINSCALE1 = 3;
IF G101 = 3 THEN BACKPAINSCALE1 = 4;
IF G101 = 3 THEN BACKPAINSCALE1 = 5;
IF G101 = 3 THEN BACKPAINSCALE1 = 6;
IF G101 = 3 THEN BACKPAINSCALE1 = 7;
IF G101 = 3 THEN BACKPAINSCALE1 = 8;
IF G101 = 3 THEN BACKPAINSCALE1 = 9;
IF G101 = 3 THEN BACKPAINSCALE1 = 10;

SEVEREBODYPAIN1 = .;
IF G112 <1 OR G112 = . THEN SEVEREBODYPAIN1 = 0;
IF G112 = 1 THEN SEVEREBODYPAIN1 = 0;
IF G112 = 2 THEN SEVEREBODYPAIN1 = 0;
IF G112 = 3 THEN SEVEREBODYPAIN1 = 1;

*SCI;
SCI1 = .;
IF G180 LE 0 THEN SCI1 = .;
IF G180 = 1 THEN SCI1 = 1;
IF G180 = 2 THEN SCI1 = 0;

SCI2 = .;
IF WG180 LE 0 THEN SCI2 = .;
IF WG180 = 1 THEN SCI2 = 1;
IF WG180 = 2 THEN SCI2 = 0;

SCICHANGE = SCI2 - SCI1;

SCI = .;
IF SCI1 = 1 OR SCI2 = 1 THEN SCI = 1;
IF SCI1 = 0 AND SCI2 = 0 THEN SCI = 0;

SCIONSET = .;
IF SCI1 = 0 AND SCI2 = 1 THEN SCIONSET = 1;
IF SCI1 = 1 AND SCI2 = 0 THEN SCIONSET = 0;
IF SCI1 = 1 AND SCI2 = 1 THEN SCIONSET = 0;

SCIREMISSION= .;
IF SCI1 = 0 AND SCI2 = 1 THEN SCIREMISSION = 0;
IF SCI1 = 1 AND SCI2 = 0 THEN SCIREMISSION = 1;
IF SCI1 = 1 AND SCI2 = 1 THEN SCIREMISSION = 0;

SCICONTINUED= .;
IF SCI1 = 0 AND SCI2 = 0 THEN SCICONTINUED = 0;
IF SCI1 = 0 AND SCI2 = 1 THEN SCICONTINUED = 0;
IF SCI1 = 1 AND SCI2 = 0 THEN SCICONTINUED = 0;
IF SCI1 = 1 AND SCI2 = 1 THEN SCICONTINUED = 1;

GDS1NOMEM = GDS1-SCI1;
GDS2NOMEM = GDS2-SCI2;

*INCLUSION VARIABLE FOR PAIN PAPER;

*CHILDHOOD VARS;
IF H14 LT 0 THEN H14=.;
CH_HEALTH=.; CH_HEALTH=H14;

DAD_READ=H2A; DAD_EDUC=H3A;
MOM_READ=H6A; MOM_EDUC=H6C;

DAD_READ=.;
IF H2A NE . THEN DO;
IF H2A EQ 1 THEN DAD_READ=1;
IF H2A EQ 2 THEN DAD_READ=0;
END;

MOM_READ=.;
IF H6A NE . THEN DO;
IF H6A EQ 1 THEN MOM_READ=1;
IF H6A EQ 2 THEN MOM_READ=0;
END;

CH_SES=.;
CH_SES=H1;

CH_ECON=.;
IF H2 NE . THEN DO;
IF H2 EQ 1 THEN CH_ECON=1;
IF H2 EQ 2 THEN CH_ECON=0;
END;

SCHOOL_WORK=.;
IF H8 NE . THEN DO;
IF H8 EQ 1 THEN SCHOOL_WORK=1;
IF H8 EQ 2 THEN SCHOOL_WORK=0;
END;

SCHOOL_HEALTH=.;
IF H15 NE . THEN DO;
IF H15 EQ 1 THEN SCHOOL_HEALTH=0;
IF H15 GE 2 THEN SCHOOL_HEALTH=1;
END;

CH_RURAL=.;
IF O2 NE . THEN DO;
CH_RURAL=0;
IF O2 EQ 1 THEN CH_RURAL=1;
END;

*LITERACY, DOC VISISTS, DIABETES MEDS OR SHOTS;
DOC_VISIT=.;
IF K25 LE 1 THEN DOC_VISIT=0;
IF K25 GT 1 THEN DOC_VISIT=1;

READ=.;
IF C8R1 NE . THEN DO;
IF C8R1 EQ 1 THEN READ=1;
IF C8R1 EQ 2 THEN READ=0;
END;
*1 MISSING READING W COG SCORE AND 2 YRS EDUC;
IF CASEID=41194210 THEN READ=0;

DIAB_MED=.;
IF G9 NE . THEN DO;
IF G9 EQ 1 THEN DIAB_MED=1;
IF G9 EQ 2 THEN DIAB_MED=0;
END;

DIAB_SHOT=.;
IF G10 NE . THEN DO;
IF G10 EQ 1 THEN DIAB_SHOT=1;
IF G10 EQ 2 THEN DIAB_SHOT=0;
END;

*1 IS GOOD FOR DIET AND CONTROL ONLY;
DIAB_DIET=.;
IF G11 NE . THEN DO;
IF G11 EQ 1 THEN DIAB_DIET=1;
IF G11 EQ 2 THEN DIAB_DIET=0;
END;

DIAB_CONTROL=.;
IF G12 NE . THEN DO;
IF G12 EQ 1 THEN DIAB_CONTROL=1;
IF G12 EQ 2 THEN DIAB_CONTROL=0;
END;

DIAB_DAILY=.;
IF G16 NE . THEN DO;
IF G16 EQ 1 THEN DIAB_DAILY=1;
IF G16 EQ 2 THEN DIAB_DAILY=0;
END;

DIAB_CIRC=.;
IF G17 NE . THEN DO;
IF G17 EQ 1 THEN DIAB_CIRC=1;
IF G17 EQ 2 THEN DIAB_CIRC=0;
END;

DIAB_VIS=.;
IF G18 NE . THEN DO;
IF G18 EQ 1 THEN DIAB_VIS=1;
IF G18 EQ 2 THEN DIAB_VIS=0;
END;

DIAB_FEET=.;
IF G19 NE . THEN DO;
IF G19 EQ 1 THEN DIAB_FEET=1;
IF G19 EQ 2 THEN DIAB_FEET=0;
END;

DIAB_AMP=.;
IF G20 NE . THEN DO;
IF G20 EQ 1 THEN DIAB_AMP=1;
IF G20 EQ 2 THEN DIAB_AMP=0;
END;

DIAB_KIDNEY=.;
IF G21 NE . THEN DO;
IF G21 EQ 1 THEN DIAB_KIDNEY=1;
IF G21 EQ 2 THEN DIAB_KIDNEY=0;
END;

FDIAB_CIRC=.;
IF YG17 NE . THEN DO;
IF YG17 EQ 1 THEN FDIAB_CIRC=1;
IF YG17 EQ 2 THEN FDIAB_CIRC=0;
END;

FDIAB_VIS=.;
IF YG18 NE . THEN DO;
IF YG18 EQ 1 THEN FDIAB_VIS=1;
IF YG18 EQ 2 THEN FDIAB_VIS=0;
END;

FDIAB_FEET=.;
IF YG19 NE . THEN DO;
IF YG19 EQ 1 THEN FDIAB_FEET=1;
IF YG19 EQ 2 THEN FDIAB_FEET=0;
END;

FDIAB_AMP=.;
IF YG20 NE . THEN DO;
IF YG20 EQ 1 THEN FDIAB_AMP=1;
IF YG20 EQ 2 THEN FDIAB_AMP=0;
END;

FDIAB_KIDNEY=.;
IF YG21 NE . THEN DO;
IF YG21 EQ 1 THEN FDIAB_KIDNEY=1;
IF YG21 EQ 2 THEN FDIAB_KIDNEY=0;
END;
*RACE1=BLACK, RACE2=MIXED, RACE3=WHITE, RACE4=INDIAN OR OTHER (RECODED BELOW);
*PROXY DID NOT REPORT RACE;
IF R2 NE . THEN DO;
RACE1=0; RACE2=0; RACE3=0; RACE4=0;
IF RACE=1 THEN RACE1=1;
IF RACE=2 THEN RACE2=1;
IF RACE=3 THEN RACE3=1;
IF RACE=4 THEN RACE4=1;
IF RACE=5 THEN RACE4=1;
END;

W_RACE=.;
IF R2 NE . THEN DO;
IF RACE=3 THEN W_RACE=1;
ELSE W_RACE=0;
END;

IF SES_LAD GT 10 THEN SES_LAD=.;

*DEPRESSIVE SX, DEP1 IS GE 5, DEP2 GE 9 (MODERATE OR SEVERE);
IF GDS1=99 THEN GDS1=.;
IF GDS2=99 THEN GDS2=.;

*ORDINAL DEPRESSION GDS;
DEP1=.;
IF GDS1 NE . THEN DO;
IF GDS1 LT 5 THEN DEP1=0;
IF GDS1 GE 5 AND GDS1 LT 9 THEN DEP1=1;
IF GDS1 GE 9 AND GDS1 LT 12 THEN DEP1=2;
IF GDS1 GE 12 THEN DEP1=3;
END;
DEP2=.;
IF GDS2 NE . THEN DO;
IF GDS2 LT 5 THEN DEP2=0;
IF GDS2 GE 5 AND GDS2 LT 9 THEN DEP2=1;
IF GDS2 GE 9 AND GDS2 LT 12 THEN DEP2=2;
IF GDS2 GE 12 THEN DEP2=3;
END;

*TEETH;
TEETH_PROB=.;
IF G126 NE . THEN DO;
IF G126=5 THEN TEETH_PROB=0;
IF G126=1 THEN TEETH_PROB=1;
IF G126 GE 2 THEN TEETH_PROB=2;
END;

ALONE = .;
IF C1NUM EQ 0 THEN ALONE =0;
IF C1NUM EQ 1 THEN ALONE = 0;
IF C1NUM EQ 2 THEN ALONE = 1;
IF C1NUM EQ 3 THEN ALONE = 1;
IF C1NUM EQ 4 THEN ALONE = 1;
IF C1NUM EQ 5 THEN ALONE = 1;
IF C1NUM EQ 6 THEN ALONE = 1;
IF C1NUM EQ 7 THEN ALONE = 1;
IF C1NUM EQ 8 THEN ALONE = 1;
IF C1NUM EQ 9 THEN ALONE = 1;
IF C1NUM EQ 10 THEN ALONE = 1;
*MARITAL;
MARITAL = .;
IF MARI_R1 = 1 THEN MARITAL = 1;
IF MARI_R1 = 2 THEN MARITAL = 1;
IF MARI_R1 GT 2 THEN MARTIAL = 0;
*ORDINAL CATEGORIES WITH MISSING FOR PARENT EDUC (1=DON'T KNOW);
MOM_EDUC0=0; MOM_EDUC1=0; MOM_EDUC2=0; MOM_EDUC3=0;
IF MOM_EDUC=. THEN MOM_EDUC0=1;
IF MOM_EDUC=0 THEN MOM_EDUC1=1;
IF MOM_EDUC=1 THEN MOM_EDUC2=1;
IF MOM_EDUC=2 THEN MOM_EDUC3=1;
DAD_EDUC0=0; DAD_EDUC1=0; DAD_EDUC2=0; DAD_EDUC3=0;
IF DAD_EDUC=. THEN DAD_EDUC0=1;
IF DAD_EDUC=0 THEN DAD_EDUC1=1;
IF DAD_EDUC=1 THEN DAD_EDUC2=1;
IF DAD_EDUC=2 THEN DAD_EDUC3=1;
*TURN MISSING RACE TO "OTHER" CATEGORY WRONG BECAUSE IF IMPAIRED
PROXY DID NOT REPORT RACE;
IF RACE=. THEN RACE=5;
IF RACE=5 THEN RACE1=0;
IF RACE=5 THEN RACE2=0;
IF RACE=5 THEN RACE3=0;
IF RACE=5 THEN RACE4=1;


*ADULT SES;
PAY_LIVING=.; PAY_HEALTH=.;
IF N71 NE . THEN DO;
IF N71=1 THEN PAY_LIVING=1;
IF N71 GT 1 THEN PAY_LIVING=0;
END;
IF N72 NE . THEN DO;
IF N72=1 THEN PAY_HEALTH=1;
IF N72 GT 1 THEN PAY_HEALTH=0;
END;
PAY_EITHER=.;
IF PAY_LIVING NE . OR PAY_HEALTH NE . THEN DO;
PAY_EITHER=0;
IF PAY_LIVING=1 THEN PAY_EITHER=1;
IF PAY_HEALTH=1 THEN PAY_EITHER=1;
END;

ALL_DATA=0;
IF (COG1 NE . AND EDUC NE . AND CH_HEALTH NE . AND CH_SES NE . AND PAY_EITHER NE .
AND CH_RURAL NE . AND CH_ECON NE .) THEN ALL_DATA=1;
RUN;

*GET SAMPLE BEFORE DELETING THOSE W MISSING EDUC OR COG FXN HERE;
*FIGURE OUT WHICH CHILDHOOD VARS MOST COMPLETE;
PROC FREQ;
WHERE COG1 NE . AND EDUC NE . AND CH_HEALTH NE . AND CH_SES NE . AND PAY_EITHER NE .
AND CH_RURAL NE . AND CH_ECON NE .;
TABLES FEM_GENDER RACE SCHOOL_HEALTH SCHOOL_WORK CH_HEALTH
MOM_READ MOM_EDUC DAD_READ DAD_EDUC CH_SES CH_ECON CH_RURAL RACE N71 N72;
RUN;

PROC FREQ;
WHERE COG1 NE . AND EDUC NE .;
TABLES COG1 PROXY PRXYRL_1;
RUN;

DATA FIVE;
SET FOUR;

IF EDUC=. THEN DELETE;
IF COG1=. THEN DELETE;

*RECODE EDUC OF 'OTHER';
IF EDUC = 17 THEN DO;
EDUC=14;
END;

*CONTINUOUS EDUCATION;
EDUC_C=EDUC;
IF EDUC GT 12 THEN DO;
IF EDUC EQ 13 THEN EDUC_C=14;
IF EDUC EQ 14 THEN EDUC_C=13;
IF EDUC EQ 15 THEN EDUC_C=16;
IF EDUC EQ 16 THEN EDUC_C=18;
END;

*EDUCATION 5-LEVEL CATEGORIES;
IF EDUC NE . THEN DO;
EDUC1=0; EDUC2=0; EDUC3=0; EDUC4=0; EDUC5=0;
IF EDUC_C LE 3 THEN EDUC1=1;
IF EDUC_C GT 3 AND EDUC_C LT 8 THEN EDUC2=1;
IF EDUC_C GT 7 AND EDUC_C LT 12 THEN EDUC3=1;
IF EDUC_C GT 11 AND EDUC_C LT 13 THEN EDUC4=1;
IF EDUC_C GE 13 THEN EDUC5=1;
END;

*AGE CATEGORIES;
IF AGE NE . THEN DO;
AGE1=0; AGE2=0; AGE3=0; AGE4=0;
IF AGE LE 69 THEN AGE1=1;
IF AGE GT 69 AND AGE LT 76 THEN AGE2=1;
IF AGE GT 75 AND AGE LT 81 THEN AGE3=1;
IF AGE GE 81 THEN AGE4=1;
END;

IF AGE NE . THEN DO;
AGE1R=0; AGE2R=0; AGE3R=0; AGE4R=0; AGE5R=0;
IF AGE LE 64 THEN AGE1R=1;
IF AGE GT 64 AND AGE LT 70 THEN AGE2R=1;
IF AGE GT 69 AND AGE LT 76 THEN AGE3R=1;
IF AGE GT 75 AND AGE LT 81 THEN AGE4R=1;
IF AGE GT 80 THEN AGE5R=1;
END;
*NUMBER IN HOME;
NUMBERHH = .;
NUMBERHH = C1NUM;

*ALONE;


*COGNITIVE DECLINE;
IF COG2 NE . THEN DO;
COGD=COG1-COG2;
END;


RUN;

/*MODEL FOR REGRESSION BASED CUTOFFS AT BASELINE--HS/VOCATIONAL EDUC IS REF
AND AGE 60-64 IS REF GROUP;
* R-SQUARE FOR CATEGORICAL VS CONTINUOUS IS SIMILAR;
PROC REG DATA=FIVE;
   MODEL COG1 = AGE2 AGE3 AGE4 EDUC1 EDUC2 EDUC3 EDUC4 FEM_GENDER READ/STB RSQUARE;
RUN;
PROC REG;
   MODEL COG1 = AGE EDUC_C FEM_GENDER READ/STB RSQUARE;
RUN;
*MODEL FOR REGRESSION BASED CUTOFFS FOR DECLINE??;
PROC REG;
   MODEL COGD = COG1 AGE EDUC_C FEM_GENDER READ/STB RSQUARE;
RUN; */

DATA SIX;
SET FIVE;

*DIABETES AGE OF ONSET MISSING FOR SOME, USING CURRENT AGE;
IF COG1 NE . AND DIAB=1 AND G8AEDAD=. THEN DO;
G8AEDAD=AGE;
END;

YRSDIAB=.;
YRSDIAB=AGE-G8AEDAD;
IF G8AEDAD EQ . THEN YRSDIAB=0;

IF DIAB=0 THEN EARLY_DIAB=0;
IF DIAB=0 THEN LATE_DIAB=0;

IF DIAB=1 THEN DO;
IF G8AEDAD GE 30 THEN LATE_DIAB=1;
IF G8AEDAD LT 30 THEN LATE_DIAB=0;
IF G8AEDAD GE 30 THEN EARLY_DIAB=0;
IF G8AEDAD LT 30 THEN EARLY_DIAB=1;
END;

DIAB_COMP=.;
DIAB_COMP=(DIAB_CIRC + DIAB_VIS + DIAB_FEET + DIAB_AMP + DIAB_KIDNEY);

DIAB_COMP2=.;
DIAB_COMP2=(FDIAB_CIRC + FDIAB_VIS + FDIAB_FEET + FDIAB_AMP + FDIAB_KIDNEY);

VASC_COMP=.;
VASC_COMP=(HTN + MI + CHF + STROKE);

VASC_COMP2=.;
VASC_COMP2=(DIAB + HTN + MI + CHF + STROKE);

DIVASC_COMP=.;
IF VASC_COMP GE 1 THEN DIVASC_COMP=1;
IF VASC_COMP LT 1 THEN DIVASC_COMP=0;

*REGRESSION BASED CUTOFFS FOR BASELINE IMPAIRMENT;
*BASED ON AGE, EDUCATION LEVEL, AND READING ON BASELINE COG MEASURES;
*WG8AE = FOLLOW UP AGE;

EXP_COG=.;
IF COG1 NE . THEN DO;
EXP_COG = 19.23297 + (-0.07861*AGE) + (0.14672*EDUC_C) + (0.27432*FEM_GENDER)
+ (1.41472*READ);
END;
INCIDENT_DEP = .;
IF GDS2 = . THEN INCIDENT_DEP = .;
IF GDS2 LT 5 THEN INCIDENT_DEP = 0;
IF GDS2 GT 4 THEN INCIDENT_DEP = 1;
COGDCAT=.;
IF COGD EQ . THEN COGDCAT = .;
IF COGD LT 1 THEN COGDCAT =0;
IF COGD EQ 1 THEN COGDCAT =1;
IF COGD EQ 2 THEN COGDCAT = 2;
IF COGD EQ 3 THEN COGDCAT = 3;
IF COGD EQ 4 THEN COGDCAT =4;
IF COGD EQ 5 THEN COGDCAT =5;
IF COGD EQ 6 THEN COGDCAT =6;
IF COGD EQ 7 THEN COGDCAT = 7;
IF COGD EQ 8 THEN COGDCAT =8;
IF COGD EQ 9 THEN COGDCAT = 9;
IF COGD EQ 10 THEN COGDCAT =10;
IF COGD EQ 11 THEN COGDCAT = 11;


COGDBIN = .;
IF COGDCAT = 0 THEN COGDBIN = 0;
IF COGDCAT >0 THEN COGDBIN = 1;


*USE AGE AT FOLLOW UP FOR INCIDENT IMPAIRMENT;
EXP_COG2=.;
EXP_COG2 = 19.23297 + (-0.07861*AGE4YR) + (0.14649*EDUC_C)  + (0.27432*FEM_GENDER)
+ (1.41472*READ);

IF COG1=. THEN EXP_COG=.;
IF COG1=. THEN EXP_COG2=.;
IF COG2=. THEN EXP_COG2=.;

COGDIFF=.;
COGDIFF=EXP_COG-COG1;

COGDIFF2=.;
COGDIFF2=EXP_COG2-COG2;

*IMPAIRMENT DEFINED BY 1.5 SD BELOW DIFFERENCE BETWEEN OBS AND EXPECTED SCORE;
*USED SD FOR COGDIFF OF 2.73 (OTHER OPTION IS TO USE SD FOR EXP_COG);
COG_IMP=.;
IF EXP_COG NE . THEN DO;
IF COGDIFF GE 4 THEN COG_IMP=1;
ELSE COG_IMP=0;
END;

COG_IMP2=.;
IF COG1 NE . AND COG2 NE . THEN DO;
IF COGDIFF2 GE 4 THEN COG_IMP2=1;
ELSE COG_IMP2=0;
END;

*CABAN CUT SCORE OF LE 10;
CI_CABAN=.;
IF COG1 NE . THEN DO;
IF COG1 GT 10 THEN CI_CABAN=0;
IF COG1 LE 10 THEN CI_CABAN=1;
END;

CDCAT = .;
IF COGDCAT NE . THEN DO;
IF COGDCAT GE 1 THEN CDCAT = 1;
IF COGDCAT LT 1 THEN CDCAT = 0;
END;

CI_CABAN2=.;
IF COG2 NE . THEN DO;
IF COG2 GT 10 THEN CI_CABAN2=0;
IF COG2 LE 10 THEN CI_CABAN2=1;
END;

*INCIDENT DEPRESSION= HIGHER CATEGORY ON ORDINAL SCALE AT FOLLOW UP;
DEPI=.;
IF DEP1 NE . AND DEP2 NE . THEN DO;
IF DEP2 GT DEP1 THEN DEPI=1;
ELSE DEPI=0;
END;

*COMORBID DEPRESSION AND COG IMP;
CO_MORB1=.;
IF COG_IMP NE . AND DIDEP1 NE . THEN DO;
IF COG_IMP=1 AND DIDEP1=1 THEN CO_MORB1=1;
ELSE CO_MORB1=0;
END;
BASELINE_DEP = .;
IF GDS1 NE . THEN DO;
IF GDS1 <5 THEN BASELINE_DEP = 0;
IF GDS1 GE 5 THEN BASELINE_DEP = 1;
END;

CO_MORB2=.;
IF COG_IMP2 NE . AND DIDEP2 NE . THEN DO;
IF COG_IMP2=1 AND DIDEP2=1 THEN CO_MORB2=1;
ELSE CO_MORB2=0;
END;

*FOLLOW UP TIME;
FU=.;
IF AGE2 NE . THEN DO;
FU=AGE2-AGE;
END;
*OCCUPATION: CODE_N18 IF MAIN JOB WAS ALSO LAST JOB, CODE_N25 IF NOT;
OCC_CODE=.;
OCC_CODE=CODE_N25;
IF CODE_N25=. THEN OCC_CODE=CODE_N18;
*GET RID OF COGNITIVE CHANGE OUTLIERS (3.5 SD GREATER THAN CHANGE)?;
*IF COGD GT 10.405 THEN COG_IMP2 = .;
*IF COGD LT -9.624 THEN COG_IMP2 = .;
RUN;

DATA SEVEN;
SET SEVEN;
PAINSTATUSB = PAINSTATUS2-PAINSTATUS1;
SCIB = SCI2-SCI1;
BODYPAINB = BODYPAIN2C - BODYPAIN1;
GDSNOMEM = GDS2NOMEM - GDS1NOMEM;
RUN;
PROC MIXED DATA = SIX COVTEST METHOD = ML;
CLASS GENDER;
MODEL COGDCAT = PAINSTATUSB AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM PAINSTATUSB/SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA = SIX COVTEST METHOD = REML;
CLASS GENDER;
MODEL COGDCAT = PAINSTATUSB AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM PAINSTATUSB/SUB=CASEID TYPE=VC;
RUN;


PROC MIXED DATA = SIX COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER;
MODEL COG2 = COG1 /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = SEVEN COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER;
MODEL COG2 = COG1 AGE /SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = SEVEN COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER;
MODEL COG2 = AGE COG1 GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM COG1 /SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = SEVEN COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER;
MODEL COG2 = COG1 PAINSTATUS1 SCI AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = EIGHT COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER CHRONICPAIN(REF = "0") NOVELPAIN(REF = "0") REMISSEDPAIN(REF = "0") ;
MODEL COGDCAT = COG1 CHRONICPAIN NOVELPAIN REMISSEDPAIN SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = HOME.SEVEN COVTEST METHOD = REML;
WHERE INCLUDE = 1 AND PAINSTATUS2 NE . AND COG2 NE .;
CLASS GENDER;
MODEL COG2 = COG1 PAINSTATUSB SCIB AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
RUN;
PROC MIXED DATA = SIX COVTEST METHOD = REML;
WHERE  COG1 NE . AND CI_CABAN NE 1 AND GDS1NOMEM NE . AND GDS1NOMEM NE 99 AND AGE NE . AND GENDER NE . AND EDUC NE . AND COG2 NE . AND CI_CABAN2 NE 1 AND DIAB NE . AND VASC_COMP NE .;
CLASS GENDER;
MODEL COG2 =  PAINSTATUS1 SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM COG1 /SUB=CASEID TYPE=VC;
RUN;

PROC GLIMMIX DATA = EIGHT;
CLASS GENDER;
MODEL SCIONSET = CHRONICPAIN REMISSEDPAIN NOVELPAIN AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP;
RANDOM PAINSTATUSB /SUB=CASEID TYPE=VC;
ESTIMATE "NOVEL" NOVELPAIN 1;
ESTIMATE "REMISSED" REMISSEDPAIN 1;
ESTIMATE "CHRONIC" CHRONICPAIN 1;
RUN;

PROC FREQ DATA = EIGHT;
TABLE NOVELPAIN REMISSEDPAIN CHRONICPAIN;
RUN;

DATA EIGHT;
SET HOME.SEVEN;
RUN;

DATA HOME.EIGHT;
SET HOME.SEVEN;
SCICONTINUED= .;
IF SCI1 = 0 AND SCI2 = 0 THEN SCICONTINUED = 0;
ELSE IF SCI1 = 0 AND SCI2 = 1 THEN SCICONTINUED = 0;
ELSE IF SCI1 = 1 AND SCI2 = 0 THEN SCICONTINUED = 0;
ELSE IF SCI1 = 1 AND SCI2 = 1 THEN SCICONTINUED = 1;
CHRONICPAIN = .;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 1 THEN CHRONICPAIN = 1;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN CHRONICPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN CHRONICPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN CHRONICPAIN = 0;

NOVELPAIN = .;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN NOVELPAIN = 1;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN NOVELPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN NOVELPAIN = 0;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 1 THEN NOVELPAIN = 0;

REMISSEDPAIN = .;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN REMISSEDPAIN = 0;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN REMISSEDPAIN = 1;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN REMISSEDPAIN = 0;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 1 THEN REMISSEDPAIN = 0;

NOPAIN = .;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 1 THEN NOPAIN = 0;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 0 THEN NOPAIN = 0;
IF PAINSTATUS1 = 0 AND PAINSTATUS2 = 0 THEN NOPAIN = 1;
IF PAINSTATUS1 = 1 AND PAINSTATUS2 = 1 THEN NOPAIN = 0;
RUN;

*CRITERIA FOR INCLUDE VARIABLE: WHERE  COG1 NE . AND CI_CABAN NE 1 AND GDS1NOMEM NE . AND GDS1NOMEM NE 99 AND AGE NE . AND GENDER NE . AND EDUC NE . AND COG2 NE . AND CI_CABAN2 NE 1 AND DIAB NE . AND VASC_COMP NE .;
DATA HOME.EIGHT;
SET HOME.EIGHT;
INCLUDE = .;
IF CASEID IN();


*DATA CONVERTED TO LONG FOR CONCURRENT ANALYSES (NINELONG);

*DESCRIPTIVES;

*PAIN CHANGES ACROSS TIME;
PROC FREQ DATA = EIGHT;
TABLE NOVELPAIN REMISSEDPAIN CHRONICPAIN;
RUN;

*FREQUENCIES ACROSS ALL BASELINE DATA;
PROC FREQ DATA= HOME.NINELONG  DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
TABLE PAINSTATUS GDSNOMEM GENDER EDUC AGE DIAB VASC_COMP;
RUN;

*CONTINUOUS DESCRIPTIVES ACROSS ALL BASELINE DATA;
PROC MEANS DATA= HOME.NINELONG N MEAN STD RANGE;
WHERE INCLUDE = 1 AND INDEX1 = 1;
VAR COG GDSNOMEM AGE EDUC VASC_COMP;
RUN;

*FREQUENCIES ACROSS BASELINE DATA FOR PEOPLE WITH PAIN;
PROC FREQ DATA= HOME.NINELONG ;
WHERE INCLUDE = 1 AND INDEX1 = 1 AND PAINSTATUS = 1;
TABLE GDSNOMEM GENDER EDUC AGE DIAB VASC_COMP GDSNOMEM;
RUN;

*FREQUENCIES ACROSS BASELINE DATA FOR PEOPLE WITHOUT PAIN;
PROC FREQ DATA= HOME.NINELONG ;
WHERE INCLUDE = 1 AND INDEX1 = 1 AND PAINSTATUS = 0;
TABLE GDSNOMEM GENDER EDUC AGE DIAB VASC_COMP;
RUN;

*CONTINUOUS BASELINE DESCRIPTIVES FOR PEOPLE WITH PAIN;
PROC MEANS DATA= HOME.NINELONG  N MEAN STD RANGE;
WHERE INCLUDE = 1 AND INDEX1 = 1 AND PAINSTATUS = 1;
VAR COG GDSNOMEM AGE EDUC VASC_COMP;
RUN;

*CONTINUOUS BASELINE DESCRIPTIVES FOR PEOPLE WITHOUT PAIN;
PROC MEANS DATA= HOME.NINELONG  N MEAN STD RANGE;
WHERE INCLUDE = 1 AND INDEX1 = 1 AND PAINSTATUS = 0;
VAR COG GDSNOMEM AGE EDUC VASC_COMP;
RUN;

*CORRELATIONS BETWEEN BASELINE VARIABLES FORTHE FULL SAMPLE;
PROC CORR DATA= HOME.SEVEN KENDALL;
WHERE INCLUDE = 1;
VAR PAINSTATUS1 SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP;
RUN;

PROC CORR DATA= HOME.NINELONG KENDALL;
WHERE INCLUDE = 1 AND INDEX1 = 1;
VAR PAINSTATUS SCI AGE GDSNOMEM GENDER EDUC DIAB VASC_COMP;
RUN;

*DESCRIPTIVE TESTING;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR COG;
RUN;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR SCI;
RUN;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR GDSNOMEM;
RUN;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR AGE;
RUN;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR EDUC;
RUN;
PROC FREQ DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
TABLES PAINSTATUS*GENDER / CHISQ;
RUN;
PROC FREQ DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
TABLES PAINSTATUS*DIAB / CHISQ;
RUN;
PROC FREQ DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
TABLES PAINSTATUS*VASC_COMP / CHISQ;
RUN;
PROC FREQ DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
TABLES PAINSTATUS*SCI / CHISQ;
RUN;
PROC TTEST DATA = HOME.NINELONG;
WHERE INCLUDE = 1 AND INDEX1 = 1;
CLASS PAINSTATUS;
VAR VASC_COMP;
RUN;




















*COGNITIVE DECLINE ANALYSES;

PROC MIXED DATA = HOME.EIGHT NOCLPRINT COVTEST METHOD = REML;
MODEL COGDCAT = / SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT /SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA = HOME.EIGHT NOCLPRINT COVTEST METHOD = REML;
WHERE INCLUDE = 1;
MODEL COGDCAT = AGE / SOLUTION DDFM=BETWITHIN;
REPEATED /SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA = HOME.EIGHT NOCLPRINT COVTEST METHOD = REML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0");
MODEL COGDCAT = COG1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP / SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA = HOME.EIGHT NOCLPRINT COVTEST METHOD = REML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0") CHRONICPAIN (REF="0") REMISSEDPAIN (REF="0") NOVELPAIN (REF="0") SCI1 (REF="0");
MODEL COGDCAT = COG1 CHRONICPAIN REMISSEDPAIN NOVELPAIN SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP / SOLUTION DDFM=BETWITHIN;
RANDOM COG1/SUB=CASEID TYPE=VC;
ESTIMATE "NOVEL" NOVELPAIN 1;
ESTIMATE "REMISSED" REMISSEDPAIN 1;
ESTIMATE "CHRONIC" CHRONICPAIN 1;
RUN;


PROC MIXED DATA = HOME.EIGHT NOCLPRINT COVTEST METHOD = REML;
CLASS GENDER;
MODEL COGDCAT = COG1 CHRONICPAIN REMISSEDPAIN NOVELPAIN|GDS1NOMEM  SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP / SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT /SUB=CASEID TYPE=VC;
ESTIMATE "NOVEL" NOVELPAIN 1;
ESTIMATE "REMISSED" REMISSEDPAIN 1;
ESTIMATE "CHRONIC" CHRONICPAIN 1;
RUN;


PROC GLIMMIX DATA = HOME.EIGHT;
CLASS GENDER;
MODEL SCI = COG1 CHRONICPAIN REMISSEDPAIN NOVELPAIN GDS1NOMEM  SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP / SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT /SUB=CASEID TYPE=VC;
ESTIMATE "NOVEL" NOVELPAIN 1;
ESTIMATE "REMISSED" REMISSEDPAIN 1;
ESTIMATE "CHRONIC" CHRONICPAIN 1;
RUN;



PROC GLIMMIX DATA = HOME.EIGHT;
CLASS GENDER;
MODEL SCI = COG1 painintensity1 paininter GDS1NOMEM  SCI1 AGE GDS1NOMEM GENDER EDUC DIAB VASC_COMP / SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT /SUB=CASEID TYPE=VC;
RUN;
*CONCURRENT COGNITION ANALYSES;
*MLM ANALYSIS;
*UNCONDITIONAL MEANS MODEL;
PROC MIXED DATA=  HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE  INCLUDE = 1;
MODEL COG= /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;

*UNCONDITIONAL GROWTH MODEL;
PROC MIXED DATA= HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE INCLUDE = 1;
CLASS GENDER;
MODEL COG= AGE /SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;
*CONDITIONAL MEANS MODEL;
PROC MIXED DATA= HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0");
MODEL COG= AGE GDSNOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;

*MAIN CONDITIONAL GROWTH MODEL;
PROC MIXED DATA= HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0") PAINSTATUS (REF="0");
MODEL COG= AGE PAINSTATUS GDSNOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA= HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0") PAINSTATUS (REF="0") SCI (REF="0");
MODEL COG= AGE PAINSTATUS|GDSNOMEM SCI GDSNOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;

PROC MIXED DATA= HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0") PAINSTATUS (REF="0") SCI (REF="0");
MODEL COG= AGE PAININTENSITY|GDSNOMEM GDSNOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;


PROC MIXED DATA= HOME.NINELONG NOCLPRINT COVTEST METHOD = ML;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0") PAINSTATUS (REF="0") SCI (REF="0");
MODEL COG= AGE PAININTER|GDSNOMEM GDSNOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;

PROC GLIMMIX DATA= HOME.EIGHT;
WHERE INCLUDE = 1;
CLASS GENDER (REF="1") DIAB (REF="0") PAINSTATUS (REF="0") SCI (REF="0");
MODEL SCI2= AGE PAINSTATUS1|PAININTER1 GDSNOMEM GDSNOMEM GENDER EDUC DIAB VASC_COMP/SOLUTION DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE=VC;
RUN;


PROC CONTENTS DATA=HOME.NINELONG;
RUN;

DATA WORK.TENLONG;
SET HOME.NINELONG;
IF G111 = 2 THEN PAINSTATUS = 0;
RUN;

*MODEL USED TO MEDIATION PROCEDURES;
PROC GLIMMIX DATA= HOME.NINELONG;
WHERE INCLUDE = 1;
MODEL SCI = AGE COG PAINSTATUS GDSNOMEM GENDER EDUC DIAB VASC_COMP /DIST=BINARY LINK=LOGIT DDFM=BETWITHIN;
RANDOM INTERCEPT/SUB=CASEID TYPE = VC;
RUN;
*HTTP://QUANTPSY.ORG/SOBEL/SOBEL.HTM*
************;























